name: CI/CD Pipeline

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs that will run in the workflow
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment (adjust if using a different language)
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'  # Specify the Python version

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run tests
      - name: Run tests
        run: |
          pytest  # Replace with your test command

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: test

    if: github.ref == 'refs/heads/main' && success()
    
    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up SSH for deployment (optional, adjust as needed)
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Deploy to production server
      - name: Deploy to Production Server
        run: |
          echo "Deploying to production server..."
          # Add your deployment commands here, e.g., SSH to server and pull the latest code
          ssh user@your-server 'cd /path/to/your/app && git pull origin main && ./deploy_script.sh'

      # Send a notification after deployment (optional)
      - name: Notify Success
        run: echo "Deployment to production was successful!"

